services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    dockerfilePath: ./docker-compose.yml
    buildFilter:
      paths:
        - docker-compose.yml
    healthCheckPath: /
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: TZ
        value: Asia/Kolkata
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com
      - key: DB_TYPE
        value: sqlite
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: sayyam
      - key: N8N_BASIC_AUTH_PASSWORD
        value: mystrongpassword
