services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    dockerComposeFilePath: ./docker-compose.yml     # ✅ Tells Render to use Docker Compose
    healthCheckPath: /
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: TZ
        value: Asia/Kolkata
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-e6ef.onrender.com           # 🔁 Update this to your real URL after deploy
      - key: DB_TYPE
        value: sqlite
