services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    dockerComposeFilePath: docker-compose.yml   # ✅ This tells Render to use docker-compose
    healthCheckPath: /
    autoDeploy: true
