services:
  - type: web
    name: n8n
    env: docker-compose   # ✅ IMPORTANT: this is the key fix
    plan: free
    region: singapore
    dockerComposeFilePath: docker-compose.yml
    healthCheckPath: /
    autoDeploy: true
